/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import FramePImage from 'src/assets/images/Group743_FrameP.png';
import { styled } from '@mui/material/styles';

const Group7431 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `812px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const Group742 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `375px`,
  height: `812px`,
  left: `0px`,
  top: `0px`,
});

const Group741 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `375px`,
  height: `812px`,
  left: `0px`,
  top: `0px`,
});

const FrameP = styled('img')({
  height: `812px`,
  width: `375px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

function Group743(props) {
  return (
    <Group7431 className={props.className}>
      <Group742>
        <Group741>
          <FrameP src={FramePImage} loading="lazy" alt={'FrameP'} />
        </Group741>
      </Group742>
    </Group7431>
  );
}

export default Group743;
